

spritesheet:
	gcc -o create_spritesheet create_spritesheet.c ../src/common/animation.c ../src/common/vector.c ../src/common/font.c ../src/common/renderer.c ../src/common/sdl.c ../src/common/lodepng.c ../src/common/files.c ../src/common/common.c -lSDL2 -lm -lGL
